development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:cbed6f805dfba48c47bf8db27dde854c@scat.redistogo.com:10705/
  channel_prefix: chat_app_rails_production
